'use client';
import { useEffect, useState } from 'react';
import { CalendarClock, CircleDollarSign, Truck, UserRound, Wrench, Wifi } from 'lucide-react';
import { Sidebar } from '@/components/sidebar';
import { Topbar } from '@/components/topbar';

type Data=any;
const euro=new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'});
export default function AuswertungenPage(){const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');useEffect(()=>{fetch('/api/reports/summary',{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Fehler');setData(p)}).catch(e=>setError(e.message))},[]);const k=data?.kpis;const cards=k?[{icon:Truck,value:k.activeVehicles,label:'Aktive Fahrzeuge',sub:`${k.archivedVehicles} im Archiv`},{icon:Wifi,value:k.samsaraConnected,label:'Samsara verbunden',sub:`von ${k.activeVehicles}`},{icon:UserRound,value:k.activeDrivers,label:'Aktive Fahrer',sub:'Personalbestand'},{icon:Wrench,value:k.openWorkshop,label:'Werkstatt offen',sub:'offene Vorgänge'},{icon:CalendarClock,value:k.overdueDeadlines,label:'Fristen überfällig',sub:`${k.nextDeadlines} in 30 Tagen`},{icon:CircleDollarSign,value:euro.format(Number(k.monthCostTotal)),label:'Kosten im Monat',sub:`${k.monthCostCount} Buchungen`}]:[];return <div className="appShell"><Sidebar/><main className="main"><Topbar title="Auswertungen" subtitle="Operative Kennzahlen aus dem Control Center"/><div className="content">
 {error&&<div className="moduleInlineMessage">{error}</div>}
 <section className="kpis reportKpis">{cards.map(card=>{const I=card.icon;return <div className="kpi" key={card.label}><div className="kpiIcon green"><I size={20}/></div><div><strong>{card.value}</strong><span>{card.label}</span><small>{card.sub}</small></div></div>})}</section>
 <div className="reportGrid"><div className="tableCard"><div className="railHead reportHead"><h3>Kosten nach Kategorie · aktueller Monat</h3></div><div className="tableWrap"><table className="moduleDataTable"><thead><tr><th>Kategorie</th><th>Buchungen</th><th>Betrag</th></tr></thead><tbody>{data?.costByCategory?.map((row:any)=><tr key={row.category}><td><span className="entityStatus">{row.category}</span></td><td>{row.count}</td><td><strong>{euro.format(Number(row.amount))}</strong></td></tr>)}{data&&!data.costByCategory?.length&&<tr><td colSpan={3} className="emptyCell">Noch keine Kosten im aktuellen Monat.</td></tr>}</tbody></table></div></div>
 <div className="tableCard"><div className="railHead reportHead"><h3>Teuerste Fahrzeuge · aktueller Monat</h3></div><div className="tableWrap"><table className="moduleDataTable"><thead><tr><th>Kennzeichen</th><th>Fahrzeug</th><th>Buchungen</th><th>Kosten</th></tr></thead><tbody>{data?.topVehicles?.map((row:any,index:number)=><tr key={row.vehicle?.id??index}><td><strong>{row.vehicle?.plate??'—'}</strong></td><td>{row.vehicle?.displayName??'—'}</td><td>{row.count}</td><td><strong>{euro.format(Number(row.amount))}</strong></td></tr>)}{data&&!data.topVehicles?.length&&<tr><td colSpan={4} className="emptyCell">Noch keine fahrzeugbezogenen Kosten.</td></tr>}</tbody></table></div></div></div>
 <div className="tableCard reportExpiry"><div className="railHead reportHead"><h3>Fahrerdokumente mit Ablauf innerhalb 60 Tagen</h3></div><div className="tableWrap"><table className="moduleDataTable"><thead><tr><th>Fahrer</th><th>Pers.-Nr.</th><th>Führerschein</th><th>Fahrerkarte</th><th>Code 95</th><th>Untersuchung</th></tr></thead><tbody>{data?.driverExpiry?.map((row:any)=><tr key={row.id}><td><strong>{row.lastName}, {row.firstName}</strong></td><td>{row.personnelNumber??'—'}</td><td>{row.licenseExpiresAt?new Date(row.licenseExpiresAt).toLocaleDateString('de-DE'):'—'}</td><td>{row.driverCardExpiresAt?new Date(row.driverCardExpiresAt).toLocaleDateString('de-DE'):'—'}</td><td>{row.code95ExpiresAt?new Date(row.code95ExpiresAt).toLocaleDateString('de-DE'):'—'}</td><td>{row.medicalExpiresAt?new Date(row.medicalExpiresAt).toLocaleDateString('de-DE'):'—'}</td></tr>)}{data&&!data.driverExpiry?.length&&<tr><td colSpan={6} className="emptyCell">Keine kritischen Fahrerdokumente.</td></tr>}</tbody></table></div></div>
 </div></main></div>}
