export type DeadlineState = 'ok' | 'warning' | 'critical' | 'none';
export type VehicleCategory = 'TRUCK' | 'VAN' | 'TRAILER' | 'SEMITRAILER' | 'OTHER';

export type Vehicle = {
  id?: string;
  plate: string;
  category?: VehicleCategory;
  vehicle: string;
  firstRegistration: string;
  location: string;
  locationAge: string;
  mileage: string;
  tuv: string;
  tuvState: DeadlineState;
  sp?: string;
  spState?: DeadlineState;
  tacho?: string;
  tachoState?: DeadlineState;
  uvv?: string;
  uvvState?: DeadlineState;
  power?: string;
  grossWeight?: string;
  camera: boolean | null;
  wrapped: boolean | null;
  samsara: boolean;
  samsaraOnline?: boolean | null;
  latitude?: number | null;
  longitude?: number | null;
  vin: string;
  inventory: string;
  insurance: string;
  taxNumber: string;
  finance: string;
  rate: string;
  documentCount?: number;
  documentsNotes?: string;
};
