'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ExternalLink, FileText, RefreshCw, Search, UploadCloud } from 'lucide-react';
import { Sidebar } from '@/components/sidebar';
import { Topbar } from '@/components/topbar';

type Driver={id:string;firstName:string;lastName:string;personnelNumber:string|null;status:string};
type Doc={id:string;type:string|null;filename:string;sizeBytes:string|null;expiresAt:string|null;createdAt:string;source:string;driver:Driver};
function size(value:string|null){const b=Number(value);if(!Number.isFinite(b)||!b)return'—';return b<1048576?`${Math.round(b/1024)} KB`:`${(b/1048576).toFixed(1)} MB`}
export default function DriverDocumentsPage(){
 const [drivers,setDrivers]=useState<Driver[]>([]);const [docs,setDocs]=useState<Doc[]>([]);const [query,setQuery]=useState('');const [message,setMessage]=useState('');const [uploading,setUploading]=useState(false);const [canUpload,setCanUpload]=useState(false);
 async function load(){setMessage('');try{const [dr,dd]=await Promise.all([fetch('/api/drivers',{cache:'no-store'}),fetch('/api/driver-documents',{cache:'no-store'})]);const a=await dr.json(),b=await dd.json();if(!dr.ok)throw new Error(a.error||'Fahrer konnten nicht geladen werden.');if(!dd.ok)throw new Error(b.error||'Dokumente konnten nicht geladen werden.');setDrivers(a.drivers??[]);setDocs(b.documents??[])}catch(error){setMessage(error instanceof Error?error.message:'Fehler beim Laden.')}}
 useEffect(()=>{void load();fetch('/api/auth/me').then(r=>r.ok?r.json():null).then(p=>setCanUpload(['ADMIN','PERSONAL'].includes(p?.user?.role))).catch(()=>setCanUpload(false))},[]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?docs.filter(row=>[row.driver.lastName,row.driver.firstName,row.driver.personnelNumber,row.type,row.filename].join(' ').toLowerCase().includes(q)):docs},[docs,query]);
 async function upload(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!canUpload)return;const form=new FormData(event.currentTarget);const driverId=String(form.get('driverId')||'');if(!driverId)return;form.delete('driverId');setUploading(true);setMessage('');try{const response=await fetch(`/api/drivers/${driverId}/documents`,{method:'POST',body:form});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Upload fehlgeschlagen.');event.currentTarget.reset();await load()}catch(error){setMessage(error instanceof Error?error.message:'Upload fehlgeschlagen.')}finally{setUploading(false)}}
 async function open(id:string){const response=await fetch(`/api/driver-documents/${id}/open`);const payload=await response.json().catch(()=>({}));if(!response.ok){setMessage(payload.error||'Dokument konnte nicht geöffnet werden.');return}window.open(payload.url,'_blank','noopener,noreferrer')}
 return <div className="appShell"><Sidebar/><main className="main"><Topbar title="Fahrerdokumente" subtitle="Dokumente und Nachweise in MEGA S4"/><div className="content">
  <div className="driverDocsGrid"><div className="tableCard moduleEntityCard"><div className="moduleToolbar"><div className="moduleSearch"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Fahrer, Personalnummer, Dokument ..."/></div><span className="moduleCounter">{filtered.length} Dateien</span><div className="filterSpacer"/><button className="filterBtn" onClick={()=>void load()}><RefreshCw size={14}/>Aktualisieren</button></div>{message&&<div className="moduleInlineMessage">{message}</div>}<div className="tableWrap"><table className="moduleDataTable"><thead><tr><th>Fahrer</th><th>Pers.-Nr.</th><th>Typ</th><th>Datei</th><th>Größe</th><th>Gültig bis</th><th>Quelle</th><th></th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><strong>{row.driver.lastName}, {row.driver.firstName}</strong></td><td>{row.driver.personnelNumber??'—'}</td><td><span className="entityStatus">{row.type??'SONSTIGE'}</span></td><td>{row.filename}</td><td>{size(row.sizeBytes)}</td><td>{row.expiresAt?new Date(row.expiresAt).toLocaleDateString('de-DE'):'—'}</td><td>{row.source}</td><td><button className="restoreBtn" onClick={()=>void open(row.id)}><ExternalLink size={13}/>Öffnen</button></td></tr>)}{!filtered.length&&<tr><td colSpan={8} className="emptyCell">Noch keine Fahrerdokumente.</td></tr>}</tbody></table></div></div>
  <aside className="rightRail">{canUpload?<form className="railCard driverUploadCard" onSubmit={upload}><div className="railHead"><h3>Dokument hochladen</h3><UploadCloud size={16}/></div><label><span>Fahrer</span><select name="driverId" required defaultValue=""><option value="" disabled>Fahrer auswählen</option>{drivers.filter(d=>d.status==='ACTIVE').map(d=><option key={d.id} value={d.id}>{d.lastName}, {d.firstName}{d.personnelNumber?` · ${d.personnelNumber}`:''}</option>)}</select></label><label><span>Dokumenttyp</span><select name="type" defaultValue="FUEHRERSCHEIN"><option value="FUEHRERSCHEIN">Führerschein</option><option value="FAHRERKARTE">Fahrerkarte</option><option value="CODE95">Code 95</option><option value="MEDIZIN">Ärztliche Untersuchung</option><option value="AUSWEIS">Ausweis</option><option value="VERTRAG">Vertrag</option><option value="SONSTIGE">Sonstiges</option></select></label><label><span>Gültig bis</span><input name="expiresAt" type="date"/></label><label><span>Datei</span><input name="file" type="file" required accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx"/></label><button className="greenBtn driverUploadButton" disabled={uploading}><FileText size={14}/>{uploading?'Upload ...':'In MEGA S4 speichern'}</button></form>:<div className="railCard infoRail"><h3>Nur Lesen</h3><p>Dokumente können von Personal und Administratoren hochgeladen werden.</p></div>}</aside></div>
 </div></main></div>}
