'use client';

import { FormEvent, useEffect, useState } from 'react';
import { RefreshCw, Send, TriangleAlert } from 'lucide-react';

type Template={id:string;name:string;language:string;status:string;category:string;qualityScore:string|null};

export function MetaTemplateManager(){
  const [templates,setTemplates]=useState<Template[]>([]);const [configured,setConfigured]=useState<boolean|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
  async function load(){setLoading(true);setMessage('');try{const response=await fetch('/api/integrations/meta/templates');const payload=await response.json().catch(()=>({}));setConfigured(Boolean(payload.configured));setTemplates(payload.templates??[]);if(!response.ok&&payload.error)setMessage(payload.error)}catch{setConfigured(false);setMessage('Meta Status konnte nicht geladen werden.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setSaving(true);setMessage('');try{const response=await fetch('/api/integrations/meta/templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:form.get('name'),language:form.get('language'),category:form.get('category'),body:form.get('body')})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||'Meta Template konnte nicht erstellt werden.');setMessage(`Template ${payload.name} wurde an Meta gesendet (${payload.status||'PENDING'}).`);event.currentTarget.reset();await load()}catch(error){setMessage(error instanceof Error?error.message:'Meta Template konnte nicht erstellt werden.')}finally{setSaving(false)}}
  return <section className="metaManager">
    <div className="moduleTable tableCard"><div className="moduleToolbar"><div><strong>Meta WhatsApp Templates</strong><small>{configured===false?'Nicht konfiguriert':`${templates.length} Templates aus Meta`}</small></div><div className="filterSpacer"/><button className="filterBtn" onClick={()=>void load()} disabled={loading}><RefreshCw size={14}/>{loading?'Laden ...':'Aktualisieren'}</button></div>
      {configured===false?<div className="integrationNotice"><TriangleAlert size={17}/><div><strong>Meta noch nicht konfiguriert</strong><span>WABA ID und Access Token werden später ausschließlich über `.env` gesetzt.</span></div></div>:<div className="tableWrap"><table className="moduleDataTable"><thead><tr><th>Name</th><th>Sprache</th><th>Kategorie</th><th>Status</th><th>Qualität</th></tr></thead><tbody>{templates.map(row=><tr key={row.id||`${row.name}-${row.language}`}><td><strong>{row.name}</strong></td><td>{row.language}</td><td>{row.category}</td><td><span className={`archiveStatus ${String(row.status).toLowerCase()==='approved'?'sold':'archived'}`}>{row.status}</span></td><td>{row.qualityScore||'—'}</td></tr>)}{!templates.length&&!loading&&<tr><td colSpan={5} className="emptyCell">Keine Meta Templates vorhanden.</td></tr>}</tbody></table></div>}
    </div>
    <aside className="rightRail"><form className="railCard driverUploadCard" onSubmit={submit}><div className="railHead"><h3>Neues Meta Template</h3></div><label><span>Name</span><input name="name" required placeholder="lts_tuv_reminder" pattern="[a-z0-9_]+"/></label><label><span>Sprache</span><input name="language" defaultValue="de" required/></label><label><span>Kategorie</span><select name="category" defaultValue="UTILITY"><option value="UTILITY">Utility</option><option value="MARKETING">Marketing</option><option value="AUTHENTICATION">Authentication</option></select></label><label><span>Body</span><textarea name="body" rows={6} required placeholder="Hallo {{1}}, ..."/></label><button className="greenBtn driverUploadButton" disabled={saving||configured===false}><Send size={14}/>{saving?'Senden ...':'An Meta senden'}</button>{message&&<p className="formMessage">{message}</p>}</form></aside>
  </section>
}
